# Generated by Django 4.2 on 2023-05-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ticker', models.CharField(max_length=120)),
                ('openPrice', models.FloatField()),
                ('closePrice', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
            ],
        ),
    ]
