# Generated by Django 4.2 on 2023-05-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockreports', '0003_rename_stockreports_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='dashboardId',
            field=models.IntegerField(default=1),
        ),
    ]
