# Generated by Django 4.2 on 2023-05-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockreports', '0004_stocks_dashboardid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='dashboardName',
            field=models.CharField(default='main', max_length=120),
        ),
    ]
