# Generated by Django 4.2 on 2023-05-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockreports', '0005_stocks_dashboardname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='closePrice',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='high',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='low',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='openPrice',
        ),
    ]
